### PR TITLE
Chris

### PR DESCRIPTION
**Pull request by cdelauder**
I just can't bring myself to add a gif to a ups pull request. I would rather no one notice I fucked with this.

### CODE REVIEW

**Comment by tddyco** [comment]
so this disables file hashing, which is a primary feature of ups...?

**Comment by cdelauder** [comment]
Sorry, I forgot this was open sourced, and was only thinking about our current needs. I have made some changes so it will remain backwards compatible. However, we want to eliminate the hashing because we need to be able to update the build without a server restart. Therefore we need predictable file names for our assets. Our goal is to independently watch the server, client js, and client css in order to expedite development time.

**Comment by charlesfeng** [comment]
@cdelauder For private use cases, why don't you start a private fork?

**Comment by tddyco** [comment]
Since the asset manifest is simply loaded into the global template locals, you could dynamically reload this with some sort of signal passing upon finishing a UPS build. This would solve your issue without any changes to UPS itself.

**Comment by cdelauder** [comment]
Message passing would defeat the purpose. The point is to decouple the asset pipeline from the server. When you originally wrote UPS, it was an elegant solution to asset management. However, as the web has veered (maniacally off a cliff) towards SPA's, having client-side changes coupled to a server restart makes less sense. This pr is about keeping UPS relevant to the changing landscape of Javascript. Even if the majority of your changes aren't client side, the capability of only rebuilding the asset class you changed is an improvement, especially given that this is a non-breaking change.

**Comment by lukezheng** [comment]
@cdelauder @charlesfeng @tkazec I'm closing this pull request.  I decided we'll just make a fork.  Thanks for the input guys!

**Pull request closed without merging**
